version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.1-node-browsers

    steps:
      - checkout
      - run: sudo apt update 
      - run: sudo docker-php-ext-install zip 
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "composer.json" }}
            - v1-dependencies-
      - run: composer install -n --prefer-dist 
      - save_cache:
          key: v1-dependencies-{{ checksum "composer.json" }}
          paths:
            - ./vendor

  php-lint:
    docker:
      - image: circleci/php:7.1-node-browsers
    steps:
      - checkout
      - run: composer require --dev jakub-onderka/php-console-highlighter
      - run: vendor/bin/parallel-lint ./src

  deploy:
    docker:
      - image: circleci/php:7.1-node-browsers
    steps:
      - run: echo "OK Deploy"

workflows:
  version: 2
  build:
    jobs:
      - php-lint
      - build:
          requires:
            - php-lint
      - deploy:
          requires:
            - build 
          filters:
            branches:
              only: [ master ]
    